[api]
address = "127.0.0.1"
port = 8084

[recording]
fps = 30
bitrate = 4000000
recording_length_seconds = 10
segment_buffer_seconds = 2
output_directory = "recordings"

[audio]
output_device_name = ""
input_device_name  = ""

[log]
level = "info"
max_log_size = "5mb"
max_files = 5